'use client';

import { useRouter } from 'next/navigation';
import { useMemo, useState } from 'react';
import type { FinancialInputs, FxRate, ProjectionResult, ScenarioId, ScenarioParams } from '@/lib/domain/types';
import { SCENARIO_LABELS, STARTUP_CATEGORY_LABELS } from '@/lib/domain/taxonomy';
import { projectAllScenarios } from '@/lib/finance/engine';
import { convertInputs } from '@/lib/finance/currency';
import { formatMoney, formatNumber, formatPercent } from '@/lib/finance/format';
import { apiFetch } from '@/lib/client/api';
import { LineChart } from '@/components/charts/LineChart';
import { BarChart } from '@/components/charts/BarChart';
import { Button, buttonClass } from '@/components/ui/Button';
import { Card, CardHeader } from '@/components/ui/Card';
import { Disclosure } from '@/components/ui/Disclosure';
import { Notice } from '@/components/ui/Notice';
import { StatTile } from '@/components/ui/StatTile';
import { cx } from '@/components/ui/cx';
import { MoneyLinesEditor } from './MoneyLinesEditor';

const SCENARIOS: ScenarioId[] = ['konservator', 'baze', 'optimist'];
const MONTHS_SQ = ['Jan', 'Shk', 'Mar', 'Pri', 'Maj', 'Qer', 'Kor', 'Gus', 'Sht', 'Tet', 'Nën', 'Dhj'];

const num =
  'w-full min-w-0 rounded-lg border border-line-strong bg-surface px-2 py-2 text-right text-base tabular text-ink focus:border-accent focus:outline-none sm:text-sm';

function NumberField({
  id,
  label,
  value,
  onChange,
  suffix,
  min = 0,
  max,
  step = 'any',
  hint,
  disabled,
}: {
  id: string;
  label: string;
  value: number;
  onChange: (v: number) => void;
  suffix?: string;
  min?: number;
  max?: number;
  step?: string;
  hint?: string;
  disabled?: boolean;
}) {
  return (
    <div>
      <label htmlFor={id} className="mb-1 block text-xs font-medium text-muted">
        {label}
      </label>
      <div className="flex items-center gap-2">
        <input
          id={id}
          type="number"
          inputMode="decimal"
          min={min}
          max={max}
          step={step}
          disabled={disabled}
          value={Number.isFinite(value) ? value : 0}
          onChange={(e) => {
            const v = e.target.value === '' ? 0 : Number(e.target.value);
            onChange(Math.min(max ?? Infinity, Math.max(min, v)));
          }}
          className={num}
        />
        {suffix ? <span className="shrink-0 text-xs text-faint">{suffix}</span> : null}
      </div>
      {hint ? <p className="mt-0.5 text-[11px] text-faint">{hint}</p> : null}
    </div>
  );
}

/**
 * Kalkulatori i kapitalit. Every number comes from the deterministic engine (src/lib/finance);
 * nothing here is generated by AI. All assumptions are visible and editable.
 */
export function Calculator({
  initialInputs,
  fxRates,
  projectId,
  archetypeId,
  countryCode,
  isDemo,
  readOnly,
  today,
}: {
  initialInputs: FinancialInputs;
  fxRates: FxRate[];
  projectId?: string;
  archetypeId: string;
  countryCode: string;
  isDemo: boolean;
  readOnly?: boolean;
  today: string;
}) {
  const router = useRouter();
  const [inputs, setInputs] = useState<FinancialInputs>(initialInputs);
  const [scenario, setScenario] = useState<ScenarioId>('baze');
  const [dirty, setDirty] = useState(false);
  const [status, setStatus] = useState<{ tone: 'ok' | 'bad'; text: string } | null>(null);
  const [saving, setSaving] = useState(false);
  const [targetCurrency, setTargetCurrency] = useState('');
  const [manualRate, setManualRate] = useState('');
  const [manualRates, setManualRates] = useState<FxRate[]>([]);
  const [fxError, setFxError] = useState<string | null>(null);

  const results = useMemo(() => projectAllScenarios(inputs), [inputs]);
  const r: ProjectionResult = results[scenario];
  const cur = inputs.currency;

  function patch(p: Partial<FinancialInputs>) {
    setInputs((prev) => ({ ...prev, ...p }));
    setDirty(true);
    setStatus(null);
  }

  function patchScenario(id: ScenarioId, p: Partial<ScenarioParams>) {
    setInputs((prev) => ({ ...prev, scenarios: { ...prev.scenarios, [id]: { ...prev.scenarios[id], ...p } } }));
    setDirty(true);
    setStatus(null);
  }

  function changeCurrency() {
    const to = targetCurrency.trim().toUpperCase();
    if (!/^[A-Z]{3}$/.test(to) || to === cur) return;
    const rates = [...fxRates, ...manualRates];
    const res = convertInputs(inputs, to, rates, { now: new Date() });
    if (!res.ok) {
      setFxError(res.reasonSq);
      return;
    }
    setFxError(null);
    setInputs(res.inputs);
    setDirty(true);
    setStatus({ tone: 'ok', text: `U konvertua në ${to}. ${res.conversion.warningsSq.join(' ')}`.trim() });
  }

  function addManualRate() {
    const to = targetCurrency.trim().toUpperCase();
    const rate = Number(manualRate.replace(',', '.'));
    if (!/^[A-Z]{3}$/.test(to) || !(rate > 0)) {
      setFxError('Vendosni monedhën (3 shkronja) dhe një kurs më të madh se 0.');
      return;
    }
    const fx: FxRate = { base: cur, quote: to, rate, rateDate: today, sourceId: 'manual', kind: 'manuale', retrievedAt: new Date().toISOString() };
    setManualRates((prev) => [...prev.filter((x) => !(x.base === cur && x.quote === to)), fx]);
    const res = convertInputs(inputs, to, [...fxRates, ...manualRates, fx], { now: new Date() });
    if (res.ok) {
      setInputs(res.inputs);
      setDirty(true);
      setFxError(null);
      setStatus({ tone: 'ok', text: `U konvertua në ${to} me kursin manual 1 ${cur} = ${rate} ${to} (data ${today}).` });
    } else setFxError(res.reasonSq);
  }

  async function save() {
    setSaving(true);
    setStatus(null);
    try {
      if (projectId) {
        const res = await apiFetch<unknown>(`/api/projects/${projectId}`, {
          method: 'PATCH',
          body: { financialInputs: inputs, manualFxRates: manualRates },
        });
        if (!res.ok) setStatus({ tone: 'bad', text: res.messageSq });
        else {
          setDirty(false);
          setStatus({ tone: 'ok', text: 'Modeli financiar u ruajt.' });
          router.refresh();
        }
      } else {
        const res = await apiFetch<{ project: { id: string } }>('/api/projects', {
          method: 'POST',
          body: { archetypeId, countryCode, financialInputs: inputs, manualFxRates: manualRates },
        });
        if (!res.ok) setStatus({ tone: 'bad', text: res.status === 401 ? 'Plotësoni profilin ose hyni në llogari për të ruajtur projektin.' : res.messageSq });
        else router.push(`/projektet/${res.data.project.id}/kalkulatori`);
      }
    } finally {
      setSaving(false);
    }
  }

  const ue = r.unitEconomics;
  const cap = r.capital;

  return (
    <div className="space-y-5">
      {isDemo ? (
        <Notice tone="demo" title="Model me të dhëna DEMO">
          Kursi dhe treguesit e përdorur janë fiktivë. Përdoreni vetëm për të provuar kalkulatorin, jo për vendime.
        </Notice>
      ) : null}

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div role="radiogroup" aria-label="Skenari" className="flex gap-1 rounded-xl border border-line bg-surface p-1">
          {SCENARIOS.map((s) => (
            <button
              key={s}
              type="button"
              role="radio"
              aria-checked={scenario === s}
              onClick={() => setScenario(s)}
              className={cx('min-h-10 rounded-lg px-3 text-sm font-medium', scenario === s ? 'bg-accent text-white' : 'text-muted hover:text-ink')}
            >
              {SCENARIO_LABELS[s]}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2 text-sm text-muted">
          <label htmlFor="horizon">Horizonti</label>
          <select
            id="horizon"
            value={inputs.horizonMonths}
            disabled={readOnly}
            onChange={(e) => patch({ horizonMonths: Number(e.target.value) })}
            className="rounded-lg border border-line-strong bg-surface-2 px-2 py-2 text-ink"
          >
            {[12, 24, 36].map((h) => (
              <option key={h} value={h}>
                {h} muaj
              </option>
            ))}
          </select>
        </div>
      </div>

      <Card>
        <CardHeader
          title={`Rezultatet — skenari ${SCENARIO_LABELS[scenario].toLowerCase()}`}
          subtitle={`Llogaritur nga motori i aplikacionit me supozimet më poshtë · monedha ${cur}. Nuk janë garanci.`}
        />
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <StatTile label="Kapitali i nevojshëm" value={formatMoney(cap.totalRequired, cur)} note="Investimi + deficiti maksimal i parasë + rezerva" />
          <StatTile
            label="Mungesa e kapitalit"
            value={formatMoney(cap.gap, cur)}
            tone={cap.gap > 0 ? 'warn' : 'ok'}
            note={`Kapitali juaj: ${formatMoney(cap.ownCapital, cur)}`}
          />
          <StatTile
            label="Gjendja më e ulët e parasë"
            value={formatMoney(r.minCashBalance, cur)}
            tone={r.minCashBalance < 0 ? 'bad' : undefined}
            note={r.minCashMonth === null ? undefined : r.minCashMonth === 0 ? 'Pas investimit fillestar, para muajit 1' : `Në muajin ${r.minCashMonth}`}
          />
          <StatTile
            label="Pika e barazimit"
            value={ue.breakEvenCustomersPerMonth === null ? 'Nuk arrihet' : `${formatNumber(Math.ceil(ue.breakEvenCustomersPerMonth))} klientë/muaj`}
            tone={ue.breakEvenCustomersPerMonth === null ? 'bad' : undefined}
            note={ue.breakEvenUnitsPerMonth === null ? 'Kontributi për njësi ≤ 0' : `≈ ${formatNumber(ue.breakEvenUnitsPerMonth, 1)} ${inputs.unitLabelSq}/muaj`}
          />
        </div>
        <p className="mt-3 rounded-xl bg-surface-2 p-3 text-sm text-ink">{r.payback.statementSq}</p>
        {r.warningsSq.length > 0 ? (
          <ul className="mt-3 space-y-2">
            {r.warningsSq.map((w) => (
              <li key={w}>
                <Notice tone="warn">{w}</Notice>
              </li>
            ))}
          </ul>
        ) : null}
      </Card>

      <div className="grid gap-4 lg:grid-cols-2">
        <LineChart
          title="Gjendja e parasë (fund muaji)"
          subtitle="Tre skenarët në të njëjtën shkallë; nën zero = duhet kapital shtesë"
          unit={{ kind: 'money', currency: cur }}
          series={SCENARIOS.map((s) => ({
            id: s,
            label: SCENARIO_LABELS[s],
            points: results[s].rows.map((row) => ({ x: `M${row.month}`, y: row.cashBalance })),
          }))}
        />
        <BarChart
          title={`Rezultati operativ mujor — ${SCENARIO_LABELS[scenario]}`}
          subtitle="Fitimi/humbja operative (para tatimit); nuk është e njëjtë me paratë"
          unit={{ kind: 'money', currency: cur }}
          polarity
          data={r.rows.map((row) => ({ label: `M${row.month}`, value: row.operatingResult, note: MONTHS_SQ[row.calendarMonth - 1] }))}
        />
      </div>

      <Card>
        <CardHeader title="Ekonomia për njësi" subtitle={`Njësia: ${inputs.unitLabelSq}`} />
        <dl className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">
          <div>
            <dt className="text-muted">Çmimi</dt>
            <dd className="tabular text-ink">{formatMoney(ue.pricePerUnit, cur)}</dd>
          </div>
          <div>
            <dt className="text-muted">Kosto variabël</dt>
            <dd className="tabular text-ink">{formatMoney(ue.variableCostPerUnit, cur)}</dd>
          </div>
          <div>
            <dt className="text-muted">Kontributi për njësi</dt>
            <dd className={cx('tabular', ue.contributionPerUnit <= 0 ? 'text-bad' : 'text-ink')}>{formatMoney(ue.contributionPerUnit, cur)}</dd>
          </div>
          <div>
            <dt className="text-muted">Marzhi i kontributit</dt>
            <dd className="tabular text-ink">{ue.contributionMarginPct === null ? '—' : formatPercent(ue.contributionMarginPct)}</dd>
          </div>
        </dl>
        <p className={cx('mt-3 text-sm', ue.status === 'ok' ? 'text-muted' : 'text-bad')}>{ue.explanationSq}</p>
      </Card>

      <Card>
        <CardHeader title="Kapitali i nevojshëm — si llogaritet" />
        <div className="grid gap-4 md:grid-cols-2">
          <ul className="space-y-1 text-sm">
            {Object.entries(cap.byCategory).map(([k, v]) => (
              <li key={k} className="flex justify-between gap-3 border-b border-line py-1">
                <span className="text-muted">{STARTUP_CATEGORY_LABELS[k as keyof typeof STARTUP_CATEGORY_LABELS]}</span>
                <span className="tabular text-ink">{formatMoney(v, cur)}</span>
              </li>
            ))}
            <li className="flex justify-between gap-3 py-1 font-medium">
              <span className="text-ink">Investimi fillestar</span>
              <span className="tabular text-ink">{formatMoney(cap.startupTotal, cur)}</span>
            </li>
            <li className="flex justify-between gap-3 py-1">
              <span className="text-muted">+ Deficiti maksimal i parasë nga operimi</span>
              <span className="tabular text-ink">{formatMoney(cap.maxOperatingDeficit, cur)}</span>
            </li>
            <li className="flex justify-between gap-3 py-1">
              <span className="text-muted">+ Rezerva ({inputs.reserveMonths} muaj kosto fikse)</span>
              <span className="tabular text-ink">{formatMoney(cap.reserve, cur)}</span>
            </li>
            <li className="flex justify-between gap-3 border-t border-line-strong py-1 font-semibold">
              <span className="text-ink">= Kapitali i nevojshëm</span>
              <span className="tabular text-ink">{formatMoney(cap.totalRequired, cur)}</span>
            </li>
          </ul>
          <ul className="list-disc space-y-1 pl-5 text-sm text-muted">
            {cap.explanationSq.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
        </div>
      </Card>

      <Card>
        <CardHeader title="Shpenzimet e hapjes" subtitle="Hapje, pajisje, depozita, inventar fillestar, tarifa dhe testim tregu. Ndryshoni çdo vlerë me oferta reale." />
        <MoneyLinesEditor kind="startup" lines={inputs.startupCosts} currency={cur} readOnly={readOnly} today={today} onChange={(v) => patch({ startupCosts: v })} />
      </Card>

      <Card>
        <CardHeader title="Kostot fikse mujore" subtitle="Paga e pronarit trajtohet veçmas më poshtë." />
        <MoneyLinesEditor kind="monthly" lines={inputs.monthlyFixedCosts} currency={cur} readOnly={readOnly} today={today} onChange={(v) => patch({ monthlyFixedCosts: v })} />
        <div className="mt-4 grid gap-3 rounded-xl border border-line bg-surface-2/60 p-3 sm:grid-cols-2">
          <label className="flex min-h-10 items-center gap-2 text-sm text-ink">
            <input
              type="checkbox"
              checked={inputs.includeOwnerSalary}
              disabled={readOnly}
              onChange={(e) => patch({ includeOwnerSalary: e.target.checked })}
              className="h-4 w-4 accent-[var(--color-accent)]"
            />
            Përfshi pagën e pronarit në kosto
          </label>
          <NumberField
            id="ownerSalary"
            label={`Paga mujore e pronarit (${cur})`}
            value={inputs.ownerSalaryMonthly}
            disabled={readOnly || !inputs.includeOwnerSalary}
            onChange={(v) => patch({ ownerSalaryMonthly: v })}
          />
          {!inputs.includeOwnerSalary ? (
            <p className="text-xs text-warn sm:col-span-2">Paga e pronarit nuk përfshihet: rezultati operativ e mbivlerëson atë që ju mbetet realisht.</p>
          ) : null}
        </div>
      </Card>

      <Card>
        <CardHeader title="Të ardhurat dhe paraja" subtitle="Të ardhurat = sasia e shitur × çmimi. Vonesat e pagesave ndikojnë paranë, jo fitimin." />
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
          <NumberField id="price" label={`Çmimi për ${inputs.unitLabelSq} (${cur})`} value={inputs.pricePerUnit} disabled={readOnly} onChange={(v) => patch({ pricePerUnit: v })} />
          <NumberField id="vcost" label={`Kosto variabël për njësi (${cur})`} value={inputs.variableCostPerUnit} disabled={readOnly} onChange={(v) => patch({ variableCostPerUnit: v })} />
          <NumberField id="upc" label="Njësi për klient në muaj" value={inputs.unitsPerCustomerPerMonth} disabled={readOnly} onChange={(v) => patch({ unitsPerCustomerPerMonth: v })} />
          <NumberField id="own" label={`Kapitali juaj (${cur})`} value={inputs.ownCapital} disabled={readOnly} onChange={(v) => patch({ ownCapital: v })} />
          <NumberField id="coll" label="Klientët paguajnë pas" suffix="ditësh" value={inputs.collectionDays} max={180} disabled={readOnly} onChange={(v) => patch({ collectionDays: v })} />
          <NumberField id="supp" label="Ju paguani furnitorët pas" suffix="ditësh" value={inputs.supplierPaymentDays} max={120} disabled={readOnly} onChange={(v) => patch({ supplierPaymentDays: v })} />
          <NumberField id="reserve" label="Rezerva" suffix="muaj" value={inputs.reserveMonths} max={24} disabled={readOnly} onChange={(v) => patch({ reserveMonths: v })} />
          <NumberField
            id="tax"
            label="Tatimi mbi fitimin"
            suffix="%"
            value={inputs.profitTaxPct}
            max={100}
            disabled={readOnly}
            hint="Kërkon verifikim lokal"
            onChange={(v) => patch({ profitTaxPct: v })}
          />
          <div>
            <label htmlFor="startMonth" className="mb-1 block text-xs font-medium text-muted">
              Muaji i nisjes
            </label>
            <select
              id="startMonth"
              value={inputs.startMonth}
              disabled={readOnly}
              onChange={(e) => patch({ startMonth: Number(e.target.value) })}
              className="w-full rounded-lg border border-line-strong bg-surface px-2 py-2 text-ink"
            >
              {MONTHS_SQ.map((m, i) => (
                <option key={m} value={i + 1}>
                  {m}
                </option>
              ))}
            </select>
          </div>
        </div>
      </Card>

      <Card>
        <CardHeader title="Skenarët" subtitle="Supozime të dukshme dhe të ndryshueshme. Konservatori duhet të jetë vërtet i kujdesshëm." />
        <div className="table-scroll">
          <table className="w-full min-w-[560px] text-sm">
            <thead className="text-left text-xs text-faint">
              <tr>
                <th scope="col" className="py-2 pr-2">
                  Parametri
                </th>
                {SCENARIOS.map((s) => (
                  <th key={s} scope="col" className="px-2 py-2 text-right">
                    {SCENARIO_LABELS[s]}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {(
                [
                  ['startCustomers', 'Klientë në muajin 1', 1],
                  ['monthlyNewCustomers', 'Klientë të rinj në muaj', 0.5],
                  ['monthlyChurnPct', 'Largim mujor (%)', 0.5],
                  ['priceMultiplier', 'Shumëzuesi i çmimit', 0.05],
                  ['variableCostMultiplier', 'Shumëzuesi i kostos variabël', 0.05],
                  ['fixedCostMultiplier', 'Shumëzuesi i kostove fikse', 0.05],
                ] as [keyof ScenarioParams, string, number][]
              ).map(([key, label, step]) => (
                <tr key={key} className="border-t border-line">
                  <th scope="row" className="py-2 pr-2 text-left font-normal text-muted">
                    {label}
                  </th>
                  {SCENARIOS.map((s) => (
                    <td key={s} className="px-2 py-1.5">
                      <input
                        type="number"
                        inputMode="decimal"
                        step={step}
                        min={0}
                        disabled={readOnly}
                        aria-label={`${label} — ${SCENARIO_LABELS[s]}`}
                        value={Number(inputs.scenarios[s][key] ?? 0)}
                        onChange={(e) => patchScenario(s, { [key]: e.target.value === '' ? 0 : Math.max(0, Number(e.target.value)) })}
                        className={num}
                      />
                    </td>
                  ))}
                </tr>
              ))}
              <tr className="border-t border-line">
                <th scope="row" className="py-2 pr-2 text-left font-normal text-muted">
                  Vonesa e arkëtimit (ditë, bosh = si më sipër)
                </th>
                {SCENARIOS.map((s) => (
                  <td key={s} className="px-2 py-1.5">
                    <input
                      type="number"
                      inputMode="numeric"
                      min={0}
                      max={180}
                      disabled={readOnly}
                      aria-label={`Vonesa e arkëtimit — ${SCENARIO_LABELS[s]}`}
                      value={inputs.scenarios[s].collectionDaysOverride ?? ''}
                      onChange={(e) => patchScenario(s, { collectionDaysOverride: e.target.value === '' ? null : Math.max(0, Number(e.target.value)) })}
                      className={num}
                    />
                  </td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
        <Disclosure summary="Sezonaliteti (shumëzues mujor, mesatarja ≈ 1)" className="mt-4">
          <div className="grid grid-cols-3 gap-2 sm:grid-cols-6">
            {MONTHS_SQ.map((m, i) => (
              <NumberField
                key={m}
                id={`season-${i}`}
                label={m}
                step="0.05"
                value={inputs.seasonality[i] ?? 1}
                disabled={readOnly}
                onChange={(v) => {
                  const next = [...inputs.seasonality];
                  next[i] = v;
                  patch({ seasonality: next });
                }}
              />
            ))}
          </div>
        </Disclosure>
      </Card>

      <Card>
        <CardHeader title={`Parashikimi mujor — ${SCENARIO_LABELS[scenario]}`} subtitle="Fitimi (rezultati) dhe paraja (hyrje/dalje) janë gjëra të ndryshme." />
        <div className="table-scroll">
          <table className="w-full min-w-[920px] text-xs sm:text-sm">
            <thead className="text-right text-[11px] uppercase tracking-wide text-faint">
              <tr>
                <th scope="col" className="py-2 pr-2 text-left">
                  Muaji
                </th>
                <th scope="col" className="px-2">Klientë</th>
                <th scope="col" className="px-2">Njësi</th>
                <th scope="col" className="px-2">Të ardhura</th>
                <th scope="col" className="px-2">Kosto var.</th>
                <th scope="col" className="px-2">Kosto fikse</th>
                <th scope="col" className="px-2">Paga pronarit</th>
                <th scope="col" className="px-2">Rezultati op.</th>
                <th scope="col" className="px-2">Hyrje parash</th>
                <th scope="col" className="px-2">Dalje parash</th>
                <th scope="col" className="px-2">Paraja neto</th>
                <th scope="col" className="pl-2">Gjendja</th>
              </tr>
            </thead>
            <tbody className="tabular">
              {r.rows.map((row) => (
                <tr key={row.month} className="border-t border-line text-right">
                  <th scope="row" className="py-1.5 pr-2 text-left font-normal text-muted">
                    {row.month} · {MONTHS_SQ[row.calendarMonth - 1]}
                  </th>
                  <td className="px-2">{formatNumber(row.customers, 1)}</td>
                  <td className="px-2">{formatNumber(row.units, 1)}</td>
                  <td className="px-2">{formatMoney(row.revenue, cur)}</td>
                  <td className="px-2">{formatMoney(row.variableCosts, cur)}</td>
                  <td className="px-2">{formatMoney(row.fixedCosts, cur)}</td>
                  <td className="px-2">{formatMoney(row.ownerSalary, cur)}</td>
                  <td className={cx('px-2', row.operatingResult < 0 && 'text-bad')}>{formatMoney(row.operatingResult, cur)}</td>
                  <td className="px-2">{formatMoney(row.cashIn, cur)}</td>
                  <td className="px-2">{formatMoney(row.cashOut, cur)}</td>
                  <td className={cx('px-2', row.netCashFlow < 0 && 'text-bad')}>{formatMoney(row.netCashFlow, cur)}</td>
                  <td className={cx('pl-2 font-medium', row.cashBalance < 0 ? 'text-bad' : 'text-ink')}>{formatMoney(row.cashBalance, cur)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot className="tabular">
              <tr className="border-t border-line-strong text-right font-semibold">
                <th scope="row" className="py-2 pr-2 text-left">
                  Totali
                </th>
                <td className="px-2" />
                <td className="px-2" />
                <td className="px-2">{formatMoney(r.totals.revenue, cur)}</td>
                <td className="px-2">{formatMoney(r.totals.variableCosts, cur)}</td>
                <td className="px-2">{formatMoney(r.totals.fixedCosts, cur)}</td>
                <td className="px-2">{formatMoney(r.totals.ownerSalary, cur)}</td>
                <td className="px-2">{formatMoney(r.totals.operatingResult, cur)}</td>
                <td className="px-2" />
                <td className="px-2" />
                <td className="px-2">{formatMoney(r.totals.netCashFlow, cur)}</td>
                <td className="pl-2" />
              </tr>
            </tfoot>
          </table>
        </div>
        <p className="mt-2 text-xs text-faint">
          Gjendja e parasë fillon nga kapitali juaj minus investimi fillestar ({formatMoney(inputs.ownCapital - cap.startupTotal, cur)}). Nuk supozohet asnjë kredi, grant apo financim.
        </p>
      </Card>

      <Disclosure summary="Formulat e përdorura (të kontrollueshme)">
        <ul className="list-disc space-y-1 pl-5">
          {r.formulasSq.map((f) => (
            <li key={f}>{f}</li>
          ))}
        </ul>
        {inputs.assumptionsNotesSq.length > 0 ? (
          <>
            <p className="mt-3 font-medium text-ink">Shënime për supozimet</p>
            <ul className="list-disc space-y-1 pl-5">
              {inputs.assumptionsNotesSq.map((n) => (
                <li key={n}>{n}</li>
              ))}
            </ul>
          </>
        ) : null}
      </Disclosure>

      {!readOnly ? (
        <Card>
          <CardHeader title="Monedha e modelit" subtitle={`Aktualisht: ${cur}. Konvertimi përdor kurset e ruajtura me datën dhe burimin e tyre.`} />
          <div className="flex flex-wrap items-end gap-2">
            <div className="w-28">
              <label htmlFor="targetCurrency" className="mb-1 block text-xs font-medium text-muted">
                Monedha e re
              </label>
              <input
                id="targetCurrency"
                value={targetCurrency}
                maxLength={3}
                onChange={(e) => setTargetCurrency(e.target.value.toUpperCase())}
                placeholder="EUR"
                className="w-full rounded-lg border border-line-strong bg-surface px-2 py-2 text-base uppercase text-ink sm:text-sm"
              />
            </div>
            <Button type="button" variant="secondary" size="sm" onClick={changeCurrency}>
              Konverto
            </Button>
          </div>
          {fxError ? (
            <div className="mt-3 space-y-2">
              <Notice tone="warn">{fxError}</Notice>
              <div className="flex flex-wrap items-end gap-2">
                <div className="w-44">
                  <label htmlFor="manualRate" className="mb-1 block text-xs font-medium text-muted">
                    Kurs manual: 1 {cur} = ? {targetCurrency || '…'}
                  </label>
                  <input
                    id="manualRate"
                    inputMode="decimal"
                    value={manualRate}
                    onChange={(e) => setManualRate(e.target.value)}
                    className="w-full rounded-lg border border-line-strong bg-surface px-2 py-2 text-base text-ink sm:text-sm"
                  />
                </div>
                <Button type="button" variant="secondary" size="sm" onClick={addManualRate}>
                  Përdor kursin manual
                </Button>
              </div>
              <p className="text-xs text-faint">Kursi manual ruhet si “Vendosur nga ju” me datën e sotme dhe shfaqet te burimet e projektit.</p>
            </div>
          ) : null}
        </Card>
      ) : null}

      {!readOnly ? (
        <div
          className={cx(
            'z-10 flex flex-wrap items-center justify-end gap-2 rounded-2xl border border-line bg-bg/95 p-2 backdrop-blur sm:p-3',
            // Only float over the content while there is something to save.
            dirty || saving ? 'sticky bottom-20 lg:bottom-4' : '',
          )}
        >
          {status ? (
            <p role="status" className={cx('mr-auto text-sm', status.tone === 'ok' ? 'text-ok' : 'text-bad')}>
              {status.text}
            </p>
          ) : dirty ? (
            <p className="mr-auto text-sm text-warn">Ka ndryshime të paruajtura.</p>
          ) : null}
          {projectId ? (
            <a href={`/api/projects/${projectId}/export/xlsx`} className={buttonClass('secondary', 'md')}>
              Shkarko Excel
            </a>
          ) : null}
          <Button type="button" onClick={save} disabled={saving || (!!projectId && !dirty)}>
            {saving ? 'Duke ruajtur…' : projectId ? 'Ruaj modelin' : 'Ruaj si projekt'}
          </Button>
        </div>
      ) : null}
    </div>
  );
}
