/**
 * Generates src/lib/server/migrations.generated.ts from db/migrations/*.sql.
 * Serverless bundles (Netlify, Vercel) do not ship arbitrary files next to the code, so the SQL is
 * embedded; tests assert the generated file matches the .sql sources.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const dir = path.join(process.cwd(), 'db', 'migrations');
const files = readdirSync(dir)
  .filter((f) => /^\d{3,}_[a-z0-9_]+\.sql$/.test(f))
  .sort();
const entries = files.map((f) => `  { id: ${JSON.stringify(f)}, sql: ${JSON.stringify(readFileSync(path.join(dir, f), 'utf8'))} },`);
const out = `// GENERATED by scripts/embed-migrations.ts from db/migrations — do not edit by hand.\nexport const EMBEDDED_MIGRATIONS: { id: string; sql: string }[] = [\n${entries.join('\n')}\n];\n`;
writeFileSync(path.join(process.cwd(), 'src', 'lib', 'server', 'migrations.generated.ts'), out);
console.log(`Embedded ${files.length} migration(s).`);
